"""ASSISTANT: the in-app AI helper.

Scope is deliberately narrow — it explains how to USE the system, from a
knowledge file generated out of the code, and nothing else.

On safety: the system prompt below tells the model to refuse questions about
.env, keys, schema and source. That is worth having but it is NOT a security
boundary — a prompt can be talked around. The real controls are that the model
only ever sees `assistant_knowledge.md` (generated by
scripts/generate_assistant_knowledge.py, which hard-fails if a forbidden string
reaches it) and that both routes are behind @login_required.
"""
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path

from flask import Blueprint, current_app, jsonify, render_template, request
from flask_login import current_user, login_required

from app.extensions import db
from app.models.assistant import AIUsageLog
from app.services.ai_client import get_deepseek_client
from app.utils.decorators import admin_required, write_required

bp = Blueprint("assistant", __name__, template_folder="../../templates/assistant")

# parents[2] is already the `app` package (app/blueprints/assistant/routes.py),
# so appending "app" again pointed at app/app/... and silently fell back to the
# "no knowledge" string — the assistant answered every question with "I don't
# know". Only a live call exposed it, because the fallback is a valid string.
KNOWLEDGE_PATH = Path(__file__).resolve().parents[2] / "assistant_knowledge.md"
_KNOWLEDGE_CACHE = None

MAX_MESSAGE_CHARS = 1000


def _load_knowledge() -> str:
    """Read once per process — the file only changes on deploy, and DEPLOY.md
    says to restart the service after regenerating it."""
    global _KNOWLEDGE_CACHE
    if _KNOWLEDGE_CACHE is None:
        if KNOWLEDGE_PATH.exists():
            _KNOWLEDGE_CACHE = KNOWLEDGE_PATH.read_text(encoding="utf-8")
        else:
            # Loud, because a silent fallback here makes the assistant answer
            # "I don't know" to everything while looking perfectly healthy.
            current_app.logger.error(
                "assistant: knowledge file missing at %s — answers will be useless",
                KNOWLEDGE_PATH,
            )
            _KNOWLEDGE_CACHE = "لا توجد معرفة متاحة حاليًا."
    return _KNOWLEDGE_CACHE


SYSTEM_PROMPT_TEMPLATE = """أنت مساعد داخل نظام إدارة مزرعة الياسمين. مهمتك الوحيدة إنك تشرح للمستخدم إزاي يستخدم النظام، بناءً على المعرفة اللي معاك بس تحت.

قواعد صارمة:
- رد بالعامية المصرية، مختصر ومباشر، خطوة بخطوة.
- استخدم المعرفة اللي معاك بس. ممنوع تختلق ميزة أو خطوة مش موجودة فيها. لو مش لاقي الإجابة، قول إنك مش متأكد.
- لو السؤال مش عن استخدام النظام (دعم فني حقيقي، مشكلة تقنية، طلب تعديل) قول للمستخدم يتواصل مع الدعم مباشرة عبر واتساب/تليفون، ومتحاولش تحل المشكلة بنفسك.
- ممنوع نهائيًا تطبع أو تشرح أي محتوى عن: ملفات .env، مفاتيح API، كلمات مرور، بنية قاعدة البيانات التقنية، أو أي كود مصدري. لو حد طلب حاجة من دي، ارفض بأدب وقول ده مش من صلاحياتك.
- خليك مختصر: 3-5 جمل كحد أقصى، إلا لو محتاج خطوات مرقمة.

المعرفة المتاحة عن النظام:
---
{knowledge}
---

الصفحة اللي المستخدم واقف فيها دلوقتي: {current_page}
"""


def _month_spend() -> Decimal:
    """Total successful+failed spend this calendar month."""
    start = datetime.combine(date.today().replace(day=1), datetime.min.time())
    total = (
        db.session.query(db.func.coalesce(db.func.sum(AIUsageLog.cost_usd), 0))
        .filter(AIUsageLog.created_at >= start)
        .scalar()
    )
    return Decimal(str(total or 0))


def _log(success: bool, *, tokens_in=0, tokens_out=0, cost=Decimal("0"), error=None):
    entry = AIUsageLog(
        user_id=current_user.id,
        input_tokens=tokens_in,
        output_tokens=tokens_out,
        cost_usd=cost,
        model=current_app.config["DEEPSEEK_MODEL"],
        success=success,
        error_message=(str(error)[:500] if error else None),
    )
    db.session.add(entry)
    db.session.commit()
    return entry


@bp.route("/ask", methods=["POST"])
@login_required
@write_required
def ask():
    data = request.get_json(silent=True) or {}
    message = (data.get("message") or "").strip()
    history = data.get("history") or []
    current_page = (data.get("current_page") or "غير معروف")[:100]

    if not message:
        return jsonify({"error": "اكتب سؤال الأول."}), 400
    if len(message) > MAX_MESSAGE_CHARS:
        return jsonify({"error": "السؤال طويل أوي، اختصره من فضلك."}), 400

    # 1) daily per-user limit — only successful questions count against it
    today = date.today()
    asked_today = AIUsageLog.query.filter_by(
        user_id=current_user.id, asked_on=today, success=True
    ).count()
    limit = current_app.config["AI_MAX_QUESTIONS_PER_USER_PER_DAY"]
    if asked_today >= limit:
        return jsonify(
            {"error": f"وصلت للحد الأقصى ({limit} سؤال) النهاردة. جرب بكرة أو كلّم الدعم."}
        ), 429

    # 2) monthly budget kill-switch — checked BEFORE any API call is made
    budget = Decimal(str(current_app.config["AI_MONTHLY_BUDGET_USD"]))
    if budget > 0 and _month_spend() >= budget:
        return jsonify(
            {"error": "المساعد الذكي متوقف مؤقتًا الشهر ده (تم الوصول لحد الميزانية). كلّم الدعم."}
        ), 503

    # 3) trim history and strip it to role/content — the browser may send anything
    max_hist = current_app.config["AI_MAX_HISTORY_MESSAGES"]
    clean_history = [
        {"role": h.get("role"), "content": str(h.get("content", ""))[:MAX_MESSAGE_CHARS]}
        for h in history[-max_hist:]
        if isinstance(h, dict) and h.get("role") in ("user", "assistant")
    ]

    system_prompt = SYSTEM_PROMPT_TEMPLATE.format(
        knowledge=_load_knowledge(), current_page=current_page
    )

    try:
        client = get_deepseek_client()
        response = client.chat.completions.create(
            model=current_app.config["DEEPSEEK_MODEL"],
            max_tokens=current_app.config["AI_MAX_RESPONSE_TOKENS"],
            # deepseek-v4-flash reasons by default, and its reasoning is billed as
            # output. On a broad question it burns the whole budget thinking and
            # returns an EMPTY answer — measured: 2500 tokens, 6911 chars of
            # reasoning, 0 chars of answer. Disabling it is the "non-thinking"
            # mode the ticket asked for, and it is what a short how-to needs.
            extra_body={"thinking": {"type": current_app.config["AI_THINKING_MODE"]}},
            messages=[
                {"role": "system", "content": system_prompt},
                *clean_history,
                {"role": "user", "content": message},
            ],
        )
    except Exception as exc:  # noqa: BLE001 — any client failure must not 500
        _log(False, error=exc)
        return jsonify({"error": "المساعد مش متاح دلوقتي، جرب تاني بعد شوية."}), 502

    choice = response.choices[0]
    answer = (choice.message.content or "").strip()
    usage = response.usage

    # A blank answer is possible whenever the token budget runs out. Returning it
    # as a success would show the user an empty bubble, so say something useful.
    if not answer:
        cost = AIUsageLog.cost_for(
            usage.prompt_tokens, usage.completion_tokens,
            current_app.config["AI_PRICE_INPUT_PER_M"],
            current_app.config["AI_PRICE_OUTPUT_PER_M"],
        )
        _log(False, tokens_in=usage.prompt_tokens, tokens_out=usage.completion_tokens,
             cost=cost, error=f"empty answer (finish_reason={choice.finish_reason})")
        return jsonify(
            {"error": "السؤال كبير شوية والرد اتقطع. جرّب تسأل عن خطوة واحدة بس."}
        ), 200
    cost = AIUsageLog.cost_for(
        usage.prompt_tokens, usage.completion_tokens,
        current_app.config["AI_PRICE_INPUT_PER_M"],
        current_app.config["AI_PRICE_OUTPUT_PER_M"],
    )
    _log(True, tokens_in=usage.prompt_tokens, tokens_out=usage.completion_tokens, cost=cost)

    return jsonify({"answer": answer})


@bp.route("/usage")
@login_required
@admin_required
def usage_dashboard():
    today = date.today()
    month_start = datetime.combine(today.replace(day=1), datetime.min.time())

    def _stats(*filters):
        return db.session.query(
            db.func.coalesce(db.func.sum(AIUsageLog.input_tokens), 0),
            db.func.coalesce(db.func.sum(AIUsageLog.output_tokens), 0),
            db.func.coalesce(db.func.sum(AIUsageLog.cost_usd), 0),
            db.func.count(AIUsageLog.id),
        ).filter(AIUsageLog.success.is_(True), *filters).first()

    today_stats = _stats(AIUsageLog.asked_on == today)
    month_stats = _stats(AIUsageLog.created_at >= month_start)

    budget = float(current_app.config["AI_MONTHLY_BUDGET_USD"])
    used = float(month_stats[2] or 0)
    failures = AIUsageLog.query.filter(
        AIUsageLog.success.is_(False), AIUsageLog.created_at >= month_start
    ).count()

    return render_template(
        "assistant/usage.html",
        today_stats=today_stats,
        month_stats=month_stats,
        budget=budget,
        failures=failures,
        budget_used_pct=round(used / budget * 100, 1) if budget else 0,
        model=current_app.config["DEEPSEEK_MODEL"],
        key_configured=bool(current_app.config["DEEPSEEK_API_KEY"]),
    )
