"""P35 HR-2 Part 1 breeding events + status

Revision ID: 17e6e86547f4
Revises: 991faf6f6dae
Create Date: 2026-09-08 11:28:43.013601

Adds three tables (breeding_events, breeding_status_changes,
event_status_suggestions) + `cows.breeding_status` column.

Data seed: populates `event_status_suggestions` with the starting
mapping the ticket documented (event → suggested reproductive
statuses, one flagged as the UI default). Editable via admin
follow-up. Idempotent — INSERTs are guarded by NOT EXISTS.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e6e86547f4'
down_revision = '991faf6f6dae'
branch_labels = None
depends_on = None


# (event_type, event_result-or-None, suggested_status, is_default, sort_order)
_SUGGESTION_SEED = [
    ("insemination",     None,             "inseminated",   1, 0),
    ("insemination",     None,             "heifer_insem",  0, 1),
    ("pregnancy_check", "pregnant",        "pregnant",      1, 0),
    ("pregnancy_check", "pregnant",        "heifer_preg",   0, 1),
    ("pregnancy_check", "not_pregnant",    "waiting",       1, 0),
    ("pregnancy_check", "not_pregnant",    "inseminated",   0, 1),
    ("drying",           None,             "dry",           1, 0),
    ("waiting",          None,             "waiting",       1, 0),
    ("waiting",          None,             "inseminated",   0, 1),
    ("calving",          None,             "nursing",       1, 0),
    ("calving",          None,             "waiting",       0, 1),
    ("weaning",          None,             "dry",           1, 0),
    ("weaning",          None,             "inseminated",   0, 1),
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_status_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('event_result', sa.String(length=20), nullable=True),
    sa.Column('suggested_status', sa.String(length=30), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'event_result', 'suggested_status', name='uq_esm_event_status')
    )
    with op.batch_alter_table('event_status_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_status_suggestions_event_result'), ['event_result'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_status_suggestions_event_type'), ['event_type'], unique=False)

    op.create_table('breeding_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('birth_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['birth_id'], ['births.id'], ),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('breeding_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_breeding_events_birth_id'), ['birth_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_breeding_events_cow_id'), ['cow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_breeding_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_breeding_events_event_type'), ['event_type'], unique=False)

    op.create_table('breeding_status_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['breeding_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('breeding_status_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_breeding_status_changes_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_breeding_status_changes_cow_id'), ['cow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_breeding_status_changes_event_id'), ['event_id'], unique=False)

    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breeding_status', sa.String(length=30), nullable=True))

    # Seed the suggestion mapping. Each row uses NOT EXISTS on the
    # unique constraint (event_type, event_result, suggested_status)
    # so re-running the migration on a partially-populated DB is safe.
    for event_type, event_result, suggested, is_default, sort_order in _SUGGESTION_SEED:
        # SQLite doesn't allow parameterised DDL, but op.execute accepts a
        # sa.text() with bind params — portable across sqlite + postgres.
        stmt = sa.text("""
            INSERT INTO event_status_suggestions
                (event_type, event_result, suggested_status,
                 is_default, sort_order)
            SELECT :event_type, :event_result, :suggested,
                   :is_default, :sort_order
            WHERE NOT EXISTS (
                SELECT 1 FROM event_status_suggestions
                WHERE event_type = :event_type
                  AND (event_result IS :event_result OR event_result = :event_result)
                  AND suggested_status = :suggested
            )
        """)
        op.get_bind().execute(stmt, {
            "event_type": event_type,
            "event_result": event_result,
            "suggested": suggested,
            "is_default": is_default,
            "sort_order": sort_order,
        })
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.drop_column('breeding_status')

    with op.batch_alter_table('breeding_status_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breeding_status_changes_event_id'))
        batch_op.drop_index(batch_op.f('ix_breeding_status_changes_cow_id'))
        batch_op.drop_index(batch_op.f('ix_breeding_status_changes_changed_at'))

    op.drop_table('breeding_status_changes')
    with op.batch_alter_table('breeding_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breeding_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_breeding_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_breeding_events_cow_id'))
        batch_op.drop_index(batch_op.f('ix_breeding_events_birth_id'))

    op.drop_table('breeding_events')
    with op.batch_alter_table('event_status_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_status_suggestions_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_status_suggestions_event_result'))

    op.drop_table('event_status_suggestions')
    # ### end Alembic commands ###
