"""P35 HR-2 Part 3 valuation

Revision ID: 428e1f54a635
Revises: 17e6e86547f4
Create Date: 2026-09-08 11:45:57.394520

Adds `cow_valuations` history table + `cows.current_value`
column + seeds the new CoA leaf "أرباح وخسائر إعادة تقييم
الأصول" (code 4095) into any existing DB. Same idempotent
NOT-EXISTS shape as the P32 FIN-7 seed.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428e1f54a635'
down_revision = '17e6e86547f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cow_valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('prior_value', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cow_valuations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cow_valuations_cow_id'), ['cow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cow_valuations_valuation_date'), ['valuation_date'], unique=False)

    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_value', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))

    # Seed CoA leaf 4095 into any existing DB (fresh DBs get it via
    # seed_default_coa on first boot).
    op.execute("""
        INSERT INTO coa_accounts
            (code, name, name_en, type, normal_side,
             parent_id, is_postable, is_active, created_at)
        SELECT '4095', 'أرباح وخسائر إعادة تقييم الأصول',
               'Asset Revaluation P&L',
               'REVENUE', 'CREDIT',
               p.id, true, true, CURRENT_TIMESTAMP
        FROM coa_accounts p
        WHERE p.code = '4'
          AND NOT EXISTS (
              SELECT 1 FROM coa_accounts WHERE code = '4095'
          )
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.drop_column('current_value')

    with op.batch_alter_table('cow_valuations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cow_valuations_valuation_date'))
        batch_op.drop_index(batch_op.f('ix_cow_valuations_cow_id'))

    op.drop_table('cow_valuations')
    # ### end Alembic commands ###
