"""milk invoice + role-based access + labor report + first-login pw

Revision ID: 4fb2c1025c4b
Revises: 71b243f7abab
Create Date: 2026-07-19 17:01:57.023411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb2c1025c4b'
down_revision = '71b243f7abab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milk_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=40), nullable=True),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milk_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milk_invoices_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milk_invoices_invoice_number'), ['invoice_number'], unique=False)

    with op.batch_alter_table('milk_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_value', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('fat_bonus', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('protein_bonus', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('bacteria_adj', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('transport', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('other_adj', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('qty_deduction', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('cash_deduction', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('rounding', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('invoice_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_milk_deliveries_invoice_id', 'milk_invoices', ['invoice_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    with op.batch_alter_table('milk_deliveries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_milk_deliveries_invoice_id', type_='foreignkey')
        batch_op.drop_column('invoice_id')
        batch_op.drop_column('rounding')
        batch_op.drop_column('cash_deduction')
        batch_op.drop_column('qty_deduction')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('other_adj')
        batch_op.drop_column('transport')
        batch_op.drop_column('bacteria_adj')
        batch_op.drop_column('protein_bonus')
        batch_op.drop_column('fat_bonus')
        batch_op.drop_column('base_value')

    with op.batch_alter_table('milk_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milk_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_milk_invoices_customer_id'))

    op.drop_table('milk_invoices')
    # ### end Alembic commands ###
