"""HR-1 worker month bucket + closing_day

Revision ID: 991faf6f6dae
Revises: 95cc31a2098f
Create Date: 2026-09-05 12:41:59.572068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991faf6f6dae'
down_revision = '95cc31a2098f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('worker_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_month', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_worker_payments_target_month'), ['target_month'], unique=False)

    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closing_day', sa.Integer(), server_default='1', nullable=False))

    # HR-1 (PHASE 32): backfill target_month = first-of-month of
    # payment_date on every existing row, so historical payments show
    # up in the correct legacy bucket instead of falling into the
    # nullable/legacy branch. Portable date-truncation: build the
    # first-of-month from the payment_date's year/month.
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        # SQLite: strftime works on a Date column
        op.execute("""
            UPDATE worker_payments
            SET target_month = date(strftime('%Y-%m-01', payment_date))
            WHERE target_month IS NULL
        """)
    else:
        # Postgres et al: date_trunc returns a timestamp; cast back.
        op.execute("""
            UPDATE worker_payments
            SET target_month = date_trunc('month', payment_date)::date
            WHERE target_month IS NULL
        """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('closing_day')

    with op.batch_alter_table('worker_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_payments_target_month'))
        batch_op.drop_column('target_month')

    # ### end Alembic commands ###
