"""sprint 1: auth + herd + audit

Revision ID: 9bdcbaf198c0
Revises: 
Create Date: 2026-07-01 10:23:36.122155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bdcbaf198c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cattle_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_email'), ['email'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_reset_token'), ['reset_token'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('cows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ear_tag', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['cattle_groups.id'], ),
    sa.ForeignKeyConstraint(['mother_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cows_ear_tag'), ['ear_tag'], unique=True)
        batch_op.create_index(batch_op.f('ix_cows_status'), ['status'], unique=False)

    op.create_table('animal_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('buyer_name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cow_id')
    )
    with op.batch_alter_table('animal_sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_sales_sale_date'), ['sale_date'], unique=False)

    op.create_table('births',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mother_id', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('calves_count', sa.Integer(), nullable=False),
    sa.Column('delivery_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mother_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('births', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_births_birth_date'), ['birth_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_births_mother_id'), ['mother_id'], unique=False)

    op.create_table('cow_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('from_group_id', sa.Integer(), nullable=True),
    sa.Column('to_group_id', sa.Integer(), nullable=False),
    sa.Column('moved_on', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_group_id'], ['cattle_groups.id'], ),
    sa.ForeignKeyConstraint(['to_group_id'], ['cattle_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cow_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cow_movements_cow_id'), ['cow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cow_movements_moved_on'), ['moved_on'], unique=False)

    op.create_table('deaths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('death_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cow_id')
    )
    with op.batch_alter_table('deaths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deaths_death_date'), ['death_date'], unique=False)

    op.create_table('calves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birth_id', sa.Integer(), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['birth_id'], ['births.id'], ),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calves_birth_id'), ['birth_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calves_birth_id'))

    op.drop_table('calves')
    with op.batch_alter_table('deaths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deaths_death_date'))

    op.drop_table('deaths')
    with op.batch_alter_table('cow_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cow_movements_moved_on'))
        batch_op.drop_index(batch_op.f('ix_cow_movements_cow_id'))

    op.drop_table('cow_movements')
    with op.batch_alter_table('births', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_births_mother_id'))
        batch_op.drop_index(batch_op.f('ix_births_birth_date'))

    op.drop_table('births')
    with op.batch_alter_table('animal_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_sales_sale_date'))

    op.drop_table('animal_sales')
    with op.batch_alter_table('cows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cows_status'))
        batch_op.drop_index(batch_op.f('ix_cows_ear_tag'))

    op.drop_table('cows')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_reset_token'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_email'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_created_at'))

    op.drop_table('login_attempts')
    op.drop_table('cattle_groups')
    # ### end Alembic commands ###
