"""sprint 3: feed recipes + feed runs + medicine

Revision ID: c91ff9d34a80
Revises: bb3bd2f668bf
Create Date: 2026-07-01 11:00:22.157933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91ff9d34a80'
down_revision = 'bb3bd2f668bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['cattle_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feed_recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_recipes_group_id'), ['group_id'], unique=False)

    op.create_table('feed_recipe_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('kg_per_batch', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['feed_recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('batches_count', sa.Integer(), nullable=False),
    sa.Column('total_weight_kg', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_per_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['cattle_groups.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['feed_recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feed_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_runs_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_runs_run_date'), ['run_date'], unique=False)

    op.create_table('medicine_dispenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price_at_dispense', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('dispensed_on', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['cattle_groups.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicine_dispenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicine_dispenses_dispensed_on'), ['dispensed_on'], unique=False)

    op.create_table('feed_run_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('qty_used', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['feed_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_run_lines')
    with op.batch_alter_table('medicine_dispenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_dispenses_dispensed_on'))

    op.drop_table('medicine_dispenses')
    with op.batch_alter_table('feed_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_runs_run_date'))
        batch_op.drop_index(batch_op.f('ix_feed_runs_group_id'))

    op.drop_table('feed_runs')
    op.drop_table('feed_recipe_lines')
    with op.batch_alter_table('feed_recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_recipes_group_id'))

    op.drop_table('feed_recipes')
    # ### end Alembic commands ###
